image:
  file: .gitpod.Dockerfile

tasks:
  - before: command -v zsh | sudo tee -a /etc/shells \
            && sudo chsh -s $(which zsh) $USER \
            && yes | zsh setup.sh
    init: yes n | zsh setup.sh
  
